version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPO=$(aws ecr describe-repositories --repository-names sample-app --output text --query "repositories[0].repositoryUri")
      - IMAGE=$REPO:latest
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE .
  post_build:
      commands:
        - echo Build completed on `date`
        - docker push $IMAGE
        - printf '[{"name":"sample-app","ImageURI":"%s"}]' $IMAGE > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
